name: zakupyapp
description: Lista zakupowa
version: 1.6.2  # updated 27/09/2024

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.3.0
  shared_preferences: ^2.3.1
  package_info_plus: ^8.0.2
  test: ^1.25.7
  url_launcher: ^6.1.14
  provider: ^6.0.5
  diffutil_sliverlist: ^0.5.1
  http: ^1.2.2
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/