name: zakupyapp
description: Lista zakupowa
version: 1.5.3  # updated 19/01/2024

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  shared_preferences: ^2.2.1
  package_info_plus: ^5.0.1
  test: ^1.24.3
  url_launcher: ^6.1.14
  provider: ^6.0.5
  diffutil_sliverlist: ^0.5.1
  http: ^1.2.0
  firebase_auth: ^4.17.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/