name: zakupyapk
description: Lista zakupowa
version: 1.4.0  # updated 30/07/2022

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_database: ^9.0.20
  firebase_storage: ^10.3.4
  shared_preferences: ^2.0.6
  package_info_plus: ^1.4.2
  test: ^1.21.1
  url_launcher: ^6.1.5
  firebase_app_check: ^0.0.6+18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/