name: zakupyapp
description: Lista zakupowa
version: 1.5.2  # updated 17/09/2023

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_database: ^10.2.5
  firebase_storage: ^11.2.6
  firebase_app_check: ^0.1.5+2
  shared_preferences: ^2.2.1
  package_info_plus: ^4.1.0
  test: ^1.24.3
  url_launcher: ^6.1.14
  provider: ^6.0.5
  diffutil_sliverlist: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/