// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7oYZt0AbdKC4VqeOeEQbZHxtrJIqZxY',
    appId: '1:791577990847:android:707350df7ca5553fb0d80a',
    messagingSenderId: '791577990847',
    projectId: 'zakupy-apk',
    databaseURL: 'https://zakupy-apk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zakupy-apk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPPMM7vPKodIMB09gI3g72yzpbWjTatk8',
    appId: '1:791577990847:ios:d4772298df70231ab0d80a',
    messagingSenderId: '791577990847',
    projectId: 'zakupy-apk',
    databaseURL: 'https://zakupy-apk-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'zakupy-apk.appspot.com',
    iosClientId: '791577990847-ndjh3eq3thbu97v8g9dlgdui41m9lml7.apps.googleusercontent.com',
    iosBundleId: 'com.meagle.zakupyapk',
  );
}
